/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/tasks": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Create Task
         * @description Accept a Chinese ecological-monitoring request without blocking on analysis.
         */
        readonly post: operations["createTask"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tasks/{task_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Task
         * @description Reconstruct durable task, plan, step, error, and artifact state.
         */
        readonly get: operations["getTask"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tasks/{task_id}/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Stream Task Events
         * @description SSE stream. Each event id is the durable monotonic sequence and each data field is one TaskEvent JSON object. Last-Event-ID requests replay.
         */
        readonly get: operations["streamTaskEvents"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tasks/{task_id}/retry": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Retry Task
         * @description Create an immutable new attempt from a validated safe checkpoint.
         */
        readonly post: operations["retryTask"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Health */
        readonly get: operations["getAggregateHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/config/readiness": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Readiness
         * @description Report blockers without returning keys, private URLs, or other secrets.
         */
        readonly get: operations["getConfigurationReadiness"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tiles/{task_id}/{artifact_type}/{z}/{x}/{y}.png": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Artifact Tile */
        readonly get: operations["getArtifactTile"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/tasks/{task_id}/artifacts/{artifact_id}/download": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Download Artifact */
        readonly get: operations["downloadArtifact"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/internal/v1/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Agent Health
         * @description Return local process health on the private Compose network.
         */
        readonly get: operations["getAgentHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/internal/v1/data/prepare": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Prepare Data */
        readonly post: operations["prepareData"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/internal/v1/analysis/run": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Run Analysis */
        readonly post: operations["runAnalysis"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/internal/v1/quality/evaluate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Evaluate Quality */
        readonly post: operations["evaluateQuality"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/internal/v1/publisher/publish": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Publish Results */
        readonly post: operations["publishResults"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentName
         * @enum {string}
         */
        readonly AgentName: "master" | "data" | "analysis" | "quality" | "publisher";
        /** AnalysisRunCommand */
        readonly AnalysisRunCommand: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Step Id */
            readonly step_id: string;
            /** Attempt */
            readonly attempt: number;
            /**
             * Correlation Id
             * Format: uuid
             */
            readonly correlation_id: string;
            /** Inputs */
            readonly inputs: readonly components["schemas"]["DataAssetRef"][];
            /** Reuse From Attempt */
            readonly reuse_from_attempt?: number | null;
        };
        /** AnalysisRunResult */
        readonly AnalysisRunResult: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Step Id */
            readonly step_id: string;
            /** Attempt */
            readonly attempt: number;
            /**
             * Correlation Id
             * Format: uuid
             */
            readonly correlation_id: string;
            /** Artifacts */
            readonly artifacts: readonly components["schemas"]["ArtifactRef"][];
            readonly statistics: components["schemas"]["AreaStatistics"];
            /** Elapsed Ms */
            readonly elapsed_ms: number;
        };
        /** AreaStatistics */
        readonly AreaStatistics: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Increase Hectares */
            readonly increase_hectares: number;
            /** Stable Hectares */
            readonly stable_hectares: number;
            /** Decrease Hectares */
            readonly decrease_hectares: number;
            /** Valid Hectares */
            readonly valid_hectares: number;
        };
        /** ArtifactRef */
        readonly ArtifactRef: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Artifact Id
             * Format: uuid
             */
            readonly artifact_id: string;
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Attempt */
            readonly attempt: number;
            readonly artifact_type: components["schemas"]["ArtifactType"];
            readonly status: components["schemas"]["ArtifactStatus"];
            /** Media Type */
            readonly media_type: string;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Checksum Sha256 */
            readonly checksum_sha256?: string | null;
            /** Byte Size */
            readonly byte_size?: number | null;
        };
        /**
         * ArtifactStatus
         * @enum {string}
         */
        readonly ArtifactStatus: "STAGING" | "COMPLETE" | "FAILED";
        /**
         * ArtifactType
         * @enum {string}
         */
        readonly ArtifactType: "DATA_MANIFEST" | "WATERSHED_BOUNDARY" | "NDVI_BEFORE" | "NDVI_AFTER" | "NDVI_DIFFERENCE" | "CHANGE_CLASSIFICATION" | "AREA_STATISTICS" | "QUALITY_REPORT" | "PDF_REPORT";
        /** CreateTaskRequest */
        readonly CreateTaskRequest: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Query */
            readonly query: string;
        };
        /** DataAssetRef */
        readonly DataAssetRef: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            readonly dataset_id: components["schemas"]["LogicalDatasetId"];
            /** Checksum Sha256 */
            readonly checksum_sha256: string;
            /** Byte Size */
            readonly byte_size: number;
            readonly grid?: components["schemas"]["RasterGrid"] | null;
            /** Acquired On */
            readonly acquired_on?: string | null;
        };
        /** DataPrepareCommand */
        readonly DataPrepareCommand: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Step Id */
            readonly step_id: string;
            /** Attempt */
            readonly attempt: number;
            /**
             * Correlation Id
             * Format: uuid
             */
            readonly correlation_id: string;
            /** Dataset Ids */
            readonly dataset_ids: readonly components["schemas"]["LogicalDatasetId"][];
        };
        /** DataPrepareResult */
        readonly DataPrepareResult: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Step Id */
            readonly step_id: string;
            /** Attempt */
            readonly attempt: number;
            /**
             * Correlation Id
             * Format: uuid
             */
            readonly correlation_id: string;
            /** Assets */
            readonly assets: readonly components["schemas"]["DataAssetRef"][];
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        readonly ErrorCode: "VALIDATION_ERROR" | "INVALID_PLAN" | "TRANSITION_NOT_ALLOWED" | "TASK_NOT_FOUND" | "CONFLICT" | "DEPENDENCY_UNAVAILABLE" | "DATA_INVALID" | "ANALYSIS_FAILED" | "QUALITY_FAILED" | "PUBLISHING_FAILED" | "INTERNAL_ERROR";
        /** ErrorDetail */
        readonly ErrorDetail: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Field */
            readonly field?: string | null;
            /** Reason */
            readonly reason: string;
        };
        /** ErrorResponse */
        readonly ErrorResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            readonly error: components["schemas"]["StructuredError"];
        };
        /** ExecutionPlan */
        readonly ExecutionPlan: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Plan Id
             * Format: uuid
             */
            readonly plan_id: string;
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            readonly source: components["schemas"]["PlanSource"];
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            readonly model_call?: components["schemas"]["ModelCallRecord"] | null;
            /** Steps */
            readonly steps: readonly components["schemas"]["PlanStep"][];
        };
        /** HealthResponse */
        readonly HealthResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            readonly state: components["schemas"]["HealthState"];
            /**
             * Checked At
             * Format: date-time
             */
            readonly checked_at: string;
            /** Services */
            readonly services: readonly components["schemas"]["ServiceHealth"][];
        };
        /**
         * HealthState
         * @enum {string}
         */
        readonly HealthState: "HEALTHY" | "DEGRADED" | "UNAVAILABLE";
        /**
         * LogicalDatasetId
         * @enum {string}
         */
        readonly LogicalDatasetId: "watershed" | "before_red" | "before_nir" | "after_red" | "after_nir";
        /** ModelCallRecord */
        readonly ModelCallRecord: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Model */
            readonly model: string;
            /**
             * Started At
             * Format: date-time
             */
            readonly started_at: string;
            /** Duration Ms */
            readonly duration_ms: number;
            readonly status: components["schemas"]["ModelCallStatus"];
            /** Input Tokens */
            readonly input_tokens?: number | null;
            /** Output Tokens */
            readonly output_tokens?: number | null;
            /** Response Sha256 */
            readonly response_sha256?: string | null;
            /** Error Code */
            readonly error_code?: string | null;
        };
        /**
         * ModelCallStatus
         * @enum {string}
         */
        readonly ModelCallStatus: "SUCCEEDED" | "FAILED";
        /**
         * PlanSource
         * @enum {string}
         */
        readonly PlanSource: "REAL_LLM" | "BUILTIN_RECOVERY";
        /** PlanStep */
        readonly PlanStep: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Step Id */
            readonly step_id: string;
            readonly kind: components["schemas"]["PlanStepKind"];
            readonly agent: components["schemas"]["AgentName"];
            /** Order */
            readonly order: number;
            /** Title */
            readonly title: string;
            /**
             * Depends On
             * @default []
             */
            readonly depends_on: readonly string[];
        };
        /**
         * PlanStepKind
         * @enum {string}
         */
        readonly PlanStepKind: "prepare_data" | "analyze_ndvi_change" | "evaluate_quality" | "publish_results";
        /** PublishedResource */
        readonly PublishedResource: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Artifact Id
             * Format: uuid
             */
            readonly artifact_id: string;
            /** Tile Template */
            readonly tile_template?: string | null;
            /** Download Path */
            readonly download_path?: string | null;
            readonly tile_metadata?: components["schemas"]["TileMetadata"] | null;
        };
        /** PublisherPublishCommand */
        readonly PublisherPublishCommand: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Step Id */
            readonly step_id: string;
            /** Attempt */
            readonly attempt: number;
            /**
             * Correlation Id
             * Format: uuid
             */
            readonly correlation_id: string;
            /** Artifacts */
            readonly artifacts: readonly components["schemas"]["ArtifactRef"][];
            readonly quality: components["schemas"]["QualityMetrics"];
        };
        /** PublisherPublishResult */
        readonly PublisherPublishResult: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Step Id */
            readonly step_id: string;
            /** Attempt */
            readonly attempt: number;
            /**
             * Correlation Id
             * Format: uuid
             */
            readonly correlation_id: string;
            /** Resources */
            readonly resources: readonly components["schemas"]["PublishedResource"][];
            readonly report: components["schemas"]["ArtifactRef"];
        };
        /**
         * QualityConclusion
         * @enum {string}
         */
        readonly QualityConclusion: "PASS" | "WARN" | "FAIL";
        /** QualityEvaluateCommand */
        readonly QualityEvaluateCommand: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Step Id */
            readonly step_id: string;
            /** Attempt */
            readonly attempt: number;
            /**
             * Correlation Id
             * Format: uuid
             */
            readonly correlation_id: string;
            /** Artifacts */
            readonly artifacts: readonly components["schemas"]["ArtifactRef"][];
            /** Analysis Elapsed Ms */
            readonly analysis_elapsed_ms: number;
            /** Reuse From Attempt */
            readonly reuse_from_attempt?: number | null;
        };
        /** QualityEvaluateResult */
        readonly QualityEvaluateResult: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Step Id */
            readonly step_id: string;
            /** Attempt */
            readonly attempt: number;
            /**
             * Correlation Id
             * Format: uuid
             */
            readonly correlation_id: string;
            readonly metrics: components["schemas"]["QualityMetrics"];
            readonly artifact: components["schemas"]["ArtifactRef"];
        };
        /** QualityMetrics */
        readonly QualityMetrics: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Coverage Ratio */
            readonly coverage_ratio: number;
            /** Valid Pixel Ratio */
            readonly valid_pixel_ratio: number;
            /** Output Complete */
            readonly output_complete: boolean;
            /** Elapsed Ms */
            readonly elapsed_ms: number;
            readonly thresholds: components["schemas"]["QualityThresholds"];
            readonly conclusion: components["schemas"]["QualityConclusion"];
            /** Passed */
            readonly passed: boolean;
            /** Evidence */
            readonly evidence: readonly string[];
        };
        /** QualityThresholds */
        readonly QualityThresholds: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Minimum Watershed Coverage Ratio */
            readonly minimum_watershed_coverage_ratio: number;
            /** Minimum Valid Pixel Ratio */
            readonly minimum_valid_pixel_ratio: number;
            /**
             * Output Complete Required
             * @default true
             * @constant
             */
            readonly output_complete_required: true;
            /**
             * Elapsed Minimum Ms
             * @default 0
             * @constant
             */
            readonly elapsed_minimum_ms: 0;
        };
        /** RasterGrid */
        readonly RasterGrid: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Crs */
            readonly crs: string;
            /** Width */
            readonly width: number;
            /** Height */
            readonly height: number;
            /** Transform */
            readonly transform: readonly [
                number,
                number,
                number,
                number,
                number,
                number
            ];
            /** Bounds */
            readonly bounds: readonly [
                number,
                number,
                number,
                number
            ];
            /** Nodata */
            readonly nodata: number;
        };
        /**
         * ReadinessBlocker
         * @enum {string}
         */
        readonly ReadinessBlocker: "LLM_NOT_CONFIGURED" | "DATA_NOT_CONFIGURED" | "DEPENDENCY_UNAVAILABLE";
        /** ReadinessResponse */
        readonly ReadinessResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Ready */
            readonly ready: boolean;
            /** Llm Configured */
            readonly llm_configured: boolean;
            /** Data Configured */
            readonly data_configured: boolean;
            /**
             * Blockers
             * @default []
             */
            readonly blockers: readonly components["schemas"]["ReadinessBlocker"][];
            /**
             * Messages
             * @default []
             */
            readonly messages: readonly string[];
        };
        /** RetryAcceptedResponse */
        readonly RetryAcceptedResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Attempt */
            readonly attempt: number;
            readonly status: components["schemas"]["TaskStatus"];
            /**
             * Accepted At
             * Format: date-time
             */
            readonly accepted_at: string;
        };
        /** ServiceHealth */
        readonly ServiceHealth: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            readonly service: components["schemas"]["ServiceName"];
            readonly state: components["schemas"]["HealthState"];
            /**
             * Checked At
             * Format: date-time
             */
            readonly checked_at: string;
            /** Message */
            readonly message?: string | null;
        };
        /**
         * ServiceName
         * @enum {string}
         */
        readonly ServiceName: "master" | "data" | "analysis" | "quality" | "publisher" | "postgis" | "redis";
        /**
         * StepStatus
         * @enum {string}
         */
        readonly StepStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "SKIPPED";
        /** StructuredError */
        readonly StructuredError: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            readonly code: components["schemas"]["ErrorCode"];
            /** Message */
            readonly message: string;
            /** Retryable */
            readonly retryable: boolean;
            /**
             * Details
             * @default []
             */
            readonly details: readonly components["schemas"]["ErrorDetail"][];
        };
        /** TaskAcceptedResponse */
        readonly TaskAcceptedResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            readonly status: components["schemas"]["TaskStatus"];
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
        };
        /** TaskEvent */
        readonly TaskEvent: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Sequence */
            readonly sequence: number;
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Step Id */
            readonly step_id: string;
            /** Attempt */
            readonly attempt: number;
            /**
             * Correlation Id
             * Format: uuid
             */
            readonly correlation_id: string;
            readonly agent: components["schemas"]["AgentName"];
            readonly status: components["schemas"]["TaskStatus"];
            /** Progress */
            readonly progress: number;
            /** Message */
            readonly message: string;
            /** Elapsed Ms */
            readonly elapsed_ms: number;
            /**
             * Occurred At
             * Format: date-time
             */
            readonly occurred_at: string;
            readonly error?: components["schemas"]["StructuredError"] | null;
            /**
             * Artifacts
             * @default []
             */
            readonly artifacts: readonly components["schemas"]["ArtifactRef"][];
        };
        /** TaskResponse */
        readonly TaskResponse: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /**
             * Task Id
             * Format: uuid
             */
            readonly task_id: string;
            /** Query */
            readonly query: string;
            readonly status: components["schemas"]["TaskStatus"];
            /** Progress */
            readonly progress: number;
            /** Current Attempt */
            readonly current_attempt: number;
            /**
             * Correlation Id
             * Format: uuid
             */
            readonly correlation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
            readonly plan?: components["schemas"]["ExecutionPlan"] | null;
            /**
             * Steps
             * @default []
             */
            readonly steps: readonly components["schemas"]["TaskStep"][];
            /**
             * Artifacts
             * @default []
             */
            readonly artifacts: readonly components["schemas"]["ArtifactRef"][];
            readonly last_error?: components["schemas"]["StructuredError"] | null;
            readonly analysis?: components["schemas"]["AnalysisRunResult"] | null;
            readonly quality?: components["schemas"]["QualityEvaluateResult"] | null;
            readonly publication?: components["schemas"]["PublisherPublishResult"] | null;
        };
        /**
         * TaskStatus
         * @description Durable workflow states exposed by the public API.
         * @enum {string}
         */
        readonly TaskStatus: "PENDING" | "PLANNING" | "DATA_PREPARING" | "ANALYZING" | "QUALITY_CHECKING" | "PUBLISHING" | "COMPLETED" | "FAILED";
        /** TaskStep */
        readonly TaskStep: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Step Id */
            readonly step_id: string;
            readonly kind: components["schemas"]["PlanStepKind"];
            readonly agent: components["schemas"]["AgentName"];
            /** Attempt */
            readonly attempt: number;
            readonly status: components["schemas"]["StepStatus"];
            /** Progress */
            readonly progress: number;
            /** Started At */
            readonly started_at?: string | null;
            /** Completed At */
            readonly completed_at?: string | null;
            /** Elapsed Ms */
            readonly elapsed_ms?: number | null;
            readonly error?: components["schemas"]["StructuredError"] | null;
            /**
             * Artifacts
             * @default []
             */
            readonly artifacts: readonly components["schemas"]["ArtifactRef"][];
        };
        /**
         * TileArtifactType
         * @enum {string}
         */
        readonly TileArtifactType: "NDVI_BEFORE" | "NDVI_AFTER" | "NDVI_DIFFERENCE" | "CHANGE_CLASSIFICATION";
        /** TileLegendEntry */
        readonly TileLegendEntry: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            /** Value */
            readonly value: number;
            /** Label */
            readonly label: string;
            /** Color */
            readonly color: string;
        };
        /** TileMetadata */
        readonly TileMetadata: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            readonly schema_version: "1.0";
            readonly artifact_type: components["schemas"]["TileArtifactType"];
            /** Bounds Wgs84 */
            readonly bounds_wgs84: readonly [
                number,
                number,
                number,
                number
            ];
            /**
             * Start Date
             * Format: date
             */
            readonly start_date: string;
            /**
             * End Date
             * Format: date
             */
            readonly end_date: string;
            /** Units */
            readonly units: string;
            /** Attribution */
            readonly attribution: string;
            /** Legend */
            readonly legend: readonly components["schemas"]["TileLegendEntry"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly createTask: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TaskAcceptedResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly getTask: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly task_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly streamTaskEvents: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "Last-Event-ID"?: string | null;
            };
            readonly path: {
                readonly task_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "text/event-stream": string;
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly retryTask: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly task_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RetryAcceptedResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly getAggregateHealth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readonly getConfigurationReadiness: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    readonly getArtifactTile: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly task_id: string;
                readonly artifact_type: components["schemas"]["TileArtifactType"];
                readonly z: number;
                readonly x: number;
                readonly y: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "image/png": string;
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly downloadArtifact: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly task_id: string;
                readonly artifact_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/pdf": string;
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly getAgentHealth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ServiceHealth"];
                };
            };
        };
    };
    readonly prepareData: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["DataPrepareCommand"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DataPrepareResult"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly runAnalysis: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "Idempotency-Key": string;
                readonly "X-Correlation-ID": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["AnalysisRunCommand"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AnalysisRunResult"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly evaluateQuality: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "Idempotency-Key": string;
                readonly "X-Correlation-ID": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["QualityEvaluateCommand"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["QualityEvaluateResult"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly publishResults: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "Idempotency-Key": string;
                readonly "X-Correlation-ID": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PublisherPublishCommand"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PublisherPublishResult"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 500: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Structured error without secret or provider payload fields. */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
